apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: 
  name: app-routing
spec: 
  hosts: 
  - "*"
  gateways:
  - app-gateway
  http:
  - match: 
    - uri: 
        prefix: /mobile
    rewrite:
      uri: /
    route: 
    - destination: 
        host: my-svc-mobile
        port: 
          number: 80

  - match:
    - uri:
        prefix: /laptop
    rewrite:
      uri: /
    route: 
    - destination: 
        host: my-svc-laptop
        port: 
          number: 8080

  - match: 
    - uri: 
        prefix: /
    route: 
    - destination: 
        host: my-svc-home
        port: 
          number: 80
