apiVersion: v1 
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp 
spec:
  volumes:
  - name: my-vol
    persistentVolumeClaim:
      claimName: mypvc
  containers:
  - name: myapp
    image: httpd
    ports:
    - containerPort: 80 
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: my-vol
