apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels: 
    app: myapp
    env: devops
spec: 
  containers: 
    - name: mycontainer
      image: nginx:latest 
      ports: 
        - name: myport
          containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata: 
  name: my-svc
  labels: 
    app: myapp
    env: devops
spec: 
  type: NodePort
  selector: 
    app: myapp
  ports: 
    - name: myserviceport
      protocol: TCP
      port: 80
      targetPort: 80
