apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-rs
  labels:
    app: myapp
    env: devops
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: myapp
  template: 
    metadata: 
      name: myrs-pod
      labels: 
        app: myapp
        env: devops
    spec: 
      containers: 
        - name: mycontainer
          image: nginx:latest 
          ports: 
            - name: myport
              containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata: 
  name: myrs-svc
  labels: 
    app: myapp
    env: devops
spec: 
  type: NodePort
  selector: 
    app: myapp
  ports: 
    - name: myport
      protocol: TCP
      port: 80
      targetPort: 80
