apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
    env: devops
spec:
  tolerations:
    - key: "prod"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: myport
          containerPort: 80
