apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: apache-hpa
  labels: 
    app: apache
    env: devops
  namespace: apache
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics: 
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 50
