apiVersion: batch/v1
kind: Job
metadata: 
  name: myjob
  labels:
    app: myapp
    env: devops
spec: 
  parallelism: 5
  activeDeadlineSeconds: 10
  template: 
    metadata: 
      name: myjob
    spec: 
      containers: 
      - name: c01
        image: nginx:latest 
        ports: 
        - name: myport
          containerPort: 80
        command: ["/bin/bash","-c","echo mayur; sleep 30"]
      restartPolicy: Never
